name: amarillo

services:
  amarillo:
    image: ghcr.io/mfdz/amarillo:main
    env_file: ./.env.local
    ports:
      - "8080:80"
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./etc/amarillo/conf/:/app/conf/
      - ./etc/amarillo/conf/config:/app/config
      - ./var/amarillo/data/:/app/data/
      - ./var/amarillo/stops/:/app/stops/

  graphhopper:
    image: israelhikingmap/graphhopper:8.0
    ports:
      - "8989:8989"
    command: --host 0.0.0.0
    environment:
      - JAVA_OPTS=-Xmx4g
    volumes:
      - ./var/graphhopper:/data
